# Generated by Django 4.2 on 2023-04-24 17:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='events_attending', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='events_following', to=settings.AUTH_USER_MODEL),
        ),
    ]
