# Generated by Django 4.2 on 2023-04-17 18:27

import datetime
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.now,
                validators=[
                    django.core.validators.MinValueValidator(datetime.date(2023, 4, 17))
                ],
            ),
        ),
    ]
