# Generated by Django 4.2 on 2023-04-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_alter_event_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="Request",
            field=models.CharField(
                choices=[("Accept", "Accept"), ("Reject", "Reject")],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
