# Generated by Django 4.2 on 2023-04-25 20:02

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_announcement_image_alter_event_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='nationality',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='picture',
            field=models.URLField(blank=True),
        ),
    ]
