# Generated by Django 3.2.18 on 2023-04-23 21:31

import datetime
import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20230423_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, validators=[django.core.validators.MinValueValidator(datetime.date(2023, 4, 23))]),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='nationality',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
