# Generated by Django 3.2.18 on 2023-04-15 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20230415_1031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
        migrations.RemoveField(
            model_name='event',
            name='reviews',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
