# Generated by Django 4.1.7 on 2023-04-27 20:12

import datetime
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_event_attendees_alter_event_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='preferance_type',
            field=models.CharField(choices=[('General', 'General'), ('Music_Festivals', 'Music Festivals'), ('Art_Exhibitions', 'Art Exhibitions'), ('Theatre_Performances', 'Theatre Performances'), ('Dance_Shows', 'Dance Shows'), ('Film_Festivals', 'Film Festivals'), ('Marathons', 'Marathons'), ('Triathlons', 'Triathlons'), ('Football_Matches', 'Football Matches'), ('Basketball_Games', 'Basketball Games'), ('Olympic_Games', 'Olympic Games'), ('Debates', 'Debates'), ('Fundraisers', 'Fundraisers'), ('Fairs', 'Fairs'), ('Parades', 'Parades'), ('Farmers_Markets', 'Farmers Markets'), ('Charity_Events', 'Charity Events'), ('Volunteer_Events', 'Volunteer Events'), ('Fashion_Shows', 'Fashion Shows'), ('Trade_Shows', 'Trade Shows'), ('Product_Launches', 'Product Launches'), ('Runway_Shows', 'Runway Shows')], default='General', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, validators=[django.core.validators.MinValueValidator(datetime.date(2023, 4, 27))]),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('General', 'General'), ('Music_Festivals', 'Music Festivals'), ('Art_Exhibitions', 'Art Exhibitions'), ('Theatre_Performances', 'Theatre Performances'), ('Dance_Shows', 'Dance Shows'), ('Film_Festivals', 'Film Festivals'), ('Marathons', 'Marathons'), ('Triathlons', 'Triathlons'), ('Football_Matches', 'Football Matches'), ('Basketball_Games', 'Basketball Games'), ('Olympic_Games', 'Olympic Games'), ('Debates', 'Debates'), ('Fundraisers', 'Fundraisers'), ('Fairs', 'Fairs'), ('Parades', 'Parades'), ('Farmers_Markets', 'Farmers Markets'), ('Charity_Events', 'Charity Events'), ('Volunteer_Events', 'Volunteer Events'), ('Fashion_Shows', 'Fashion Shows'), ('Trade_Shows', 'Trade Shows'), ('Product_Launches', 'Product Launches'), ('Runway_Shows', 'Runway Shows')], default='General', max_length=255),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
