# Generated by Django 3.2.18 on 2023-04-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reviews',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
