# Generated by Django 4.1.7 on 2023-04-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_myuser_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='poster',
            field=models.URLField(blank=True),
        ),
    ]
