# Generated by Django 4.1.7 on 2023-04-10 09:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_event_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attendees',
        ),
        migrations.AddField(
            model_name='event',
            name='following',
            field=models.ManyToManyField(related_name='events_following', to=settings.AUTH_USER_MODEL),
        ),
    ]
