# Generated by Django 4.1.7 on 2023-04-10 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_event_image_urls'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement', models.CharField(max_length=600)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_event', to='app.event')),
            ],
        ),
    ]
