# Generated by Django 4.1.7 on 2023-04-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_announcements_announcement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='announcement',
            new_name='description',
        ),
        migrations.AddField(
            model_name='announcement',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='title',
            field=models.CharField(default='', max_length=150),
        ),
    ]
